repos:
- repo: local
  hooks:
    # flake8
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types_or: [python, pyi]
      require_serial: true

    # mypy
    - id: black
      name: black
      entry: black
      language: system
      types_or: [python, pyi]
      require_serial: true

    # isort 
    - id: isort
      name: isort
      entry: isort
      language: system
      types_or: [python, pyi]
      require_serial: true

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.2
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]